namespace generated
{
  const Obj S_x = 17;
  const Obj S_y = 33;
  const Obj S_at = 49;
  const Obj S_eq = 65;
  const Obj S_id = 81;
  const Obj S_or = 97;
  const Obj S_add = 113;
  const Obj S_amp = 129;
  const Obj S_and = 145;
  const Obj S_cat = 161;
  const Obj S_cls = 177;
  const Obj S_col = 193;
  const Obj S_den = 209;
  const Obj S_env = 225;
  const Obj S_exp = 241;
  const Obj S_idx = 257;
  const Obj S_key = 273;
  const Obj S_len = 289;
  const Obj S_map = 305;
  const Obj S_max = 321;
  const Obj S_min = 337;
  const Obj S_neg = 353;
  const Obj S_neq = 369;
  const Obj S_nil = 385;
  const Obj S_not = 401;
  const Obj S_num = 417;
  const Obj S_obj = 433;
  const Obj S_prg = 449;
  const Obj S_rat = 465;
  const Obj S_rev = 481;
  const Obj S_seq = 497;
  const Obj S_set = 513;
  const Obj S_src = 529;
  const Obj S_str = 545;
  const Obj S_tag = 561;
  const Obj S_val = 577;
  const Obj S_var = 593;
  const Obj S_body = 609;
  const Obj S_bvar = 625;
  const Obj S_case = 641;
  const Obj S_char = 657;
  const Obj S_code = 673;
  const Obj S_cond = 689;
  const Obj S_else = 705;
  const Obj S_errs = 721;
  const Obj S_eval = 737;
  const Obj S_evar = 753;
  const Obj S_expr = 769;
  const Obj S_head = 785;
  const Obj S_idiv = 801;
  const Obj S_ivar = 817;
  const Obj S_keys = 833;
  const Obj S_leaf = 849;
  const Obj S_left = 865;
  const Obj S_line = 881;
  const Obj S_list = 897;
  const Obj S_lvar = 913;
  const Obj S_map1 = 929;
  const Obj S_map2 = 945;
  const Obj S_maps = 961;
  const Obj S_mset = 977;
  const Obj S_mult = 993;
  const Obj S_name = 1009;
  const Obj S_objs = 1025;
  const Obj S_plus = 1041;
  const Obj S_ptrn = 1057;
  const Obj S_sets = 1073;
  const Obj S_size = 1089;
  const Obj S_star = 1105;
  const Obj S_svar = 1121;
  const Obj S_symb = 1137;
  const Obj S_tail = 1153;
  const Obj S_then = 1169;
  const Obj S_true = 1185;
  const Obj S_type = 1201;
  const Obj S_val1 = 1217;
  const Obj S_val2 = 1233;
  const Obj S_vals = 1249;
  const Obj S_vvar = 1265;
  const Obj S_arity = 1281;
  const Obj S_brace = 1297;
  const Obj S_cases = 1313;
  const Obj S_comma = 1329;
  const Obj S_elems = 1345;
  const Obj S_expr1 = 1361;
  const Obj S_expr2 = 1377;
  const Obj S_exprs = 1393;
  const Obj S_false = 1409;
  const Obj S_field = 1425;
  const Obj S_inner = 1441;
  const Obj S_is_eq = 1457;
  const Obj S_is_ge = 1473;
  const Obj S_is_gt = 1489;
  const Obj S_is_le = 1505;
  const Obj S_is_lt = 1521;
  const Obj S_isort = 1537;
  const Obj S_label = 1553;
  const Obj S_loops = 1569;
  const Obj S_lower = 1585;
  const Obj S_minus = 1601;
  const Obj S_no_op = 1617;
  const Obj S_outer = 1633;
  const Obj S_point = 1649;
  const Obj S_ptrns = 1665;
  const Obj S_right = 1681;
  const Obj S_slash = 1697;
  const Obj S_slice = 1713;
  const Obj S_stmts = 1729;
  const Obj S_tdefs = 1745;
  const Obj S_token = 1761;
  const Obj S_value = 1777;
  const Obj S_action = 1793;
  const Obj S_append = 1809;
  const Obj S_asgnms = 1825;
  const Obj S_branch = 1841;
  const Obj S_clause = 1857;
  const Obj S_fields = 1873;
  const Obj S_fn_def = 1889;
  const Obj S_fn_par = 1905;
  const Obj S_fndefs = 1921;
  const Obj S_get_at = 1937;
  const Obj S_header = 1953;
  const Obj S_instrs = 1969;
  const Obj S_is_int = 1985;
  const Obj S_lookup = 2001;
  const Obj S_mk_map = 2017;
  const Obj S_mk_seq = 2033;
  const Obj S_mk_set = 2049;
  const Obj S_object = 2065;
  const Obj S_offset = 2081;
  const Obj S_params = 2097;
  const Obj S_repeat = 2113;
  const Obj S_set_at = 2129;
  const Obj S_source = 2145;
  const Obj S_stream = 2161;
  const Obj S_string = 2177;
  const Obj S_symbol = 2193;
  const Obj S_to_obj = 2209;
  const Obj S_to_str = 2225;
  const Obj S_values = 2241;
  const Obj S_add_ref = 2257;
  const Obj S_bracket = 2273;
  const Obj S_cls_def = 2289;
  const Obj S_cls_var = 2305;
  const Obj S_counter = 2321;
  const Obj S_do_expr = 2337;
  const Obj S_end_val = 2353;
  const Obj S_ex_qual = 2369;
  const Obj S_fn_call = 2385;
  const Obj S_fn_defs = 2401;
  const Obj S_get_tag = 2417;
  const Obj S_greater = 2433;
  const Obj S_idx_var = 2449;
  const Obj S_if_expr = 2465;
  const Obj S_if_stmt = 2481;
  const Obj S_integer = 2497;
  const Obj S_is_expr = 2513;
  const Obj S_is_open = 2529;
  const Obj S_is_symb = 2545;
  const Obj S_or_else = 2561;
  const Obj S_or_expr = 2577;
  const Obj S_program = 2593;
  const Obj S_release = 2609;
  const Obj S_res_var = 2625;
  const Obj S_ret_val = 2641;
  const Obj S_rev_seq = 2657;
  const Obj S_set_var = 2673;
  const Obj S_symbols = 2689;
  const Obj S_syn_sgn = 2705;
  const Obj S_to_symb = 2721;
  const Obj S_typedef = 2737;
  const Obj S_accessor = 2753;
  const Obj S_all_objs = 2769;
  const Obj S_and_expr = 2785;
  const Obj S_and_then = 2801;
  const Obj S_bin_tree = 2817;
  const Obj S_brackets = 2833;
  const Obj S_branches = 2849;
  const Obj S_call_cls = 2865;
  const Obj S_cls_call = 2881;
  const Obj S_cls_expr = 2897;
  const Obj S_cls_type = 2913;
  const Obj S_dup_tdef = 2929;
  const Obj S_for_stmt = 2945;
  const Obj S_in_arity = 2961;
  const Obj S_in_types = 2977;
  const Obj S_inner_fn = 2993;
  const Obj S_integers = 3009;
  const Obj S_key_expr = 3025;
  const Obj S_key_ptrn = 3041;
  const Obj S_key_type = 3057;
  const Obj S_let_expr = 3073;
  const Obj S_let_stmt = 3089;
  const Obj S_low_ints = 3105;
  const Obj S_lower_eq = 3121;
  const Obj S_map_comp = 3137;
  const Obj S_map_expr = 3153;
  const Obj S_map_type = 3169;
  const Obj S_mk_array = 3185;
  const Obj S_nonempty = 3201;
  const Obj S_not_expr = 3217;
  const Obj S_obj_ptrn = 3233;
  const Obj S_obj_type = 3249;
  const Obj S_optional = 3265;
  const Obj S_out_type = 3281;
  const Obj S_outer_fn = 3297;
  const Obj S_patterns = 3313;
  const Obj S_ptrn_var = 3329;
  const Obj S_res_type = 3345;
  const Obj S_sel_expr = 3361;
  const Obj S_seq_comp = 3377;
  const Obj S_seq_expr = 3393;
  const Obj S_seq_iter = 3409;
  const Obj S_seq_type = 3425;
  const Obj S_set_bvar = 3441;
  const Obj S_set_comp = 3457;
  const Obj S_set_expr = 3473;
  const Obj S_set_ivar = 3489;
  const Obj S_set_type = 3505;
  const Obj S_src_expr = 3521;
  const Obj S_tag_ptrn = 3537;
  const Obj S_tag_type = 3553;
  const Obj S_tdef_err = 3569;
  const Obj S_type_any = 3585;
  const Obj S_type_ref = 3601;
  const Obj S_type_var = 3617;
  const Obj S_undef_fn = 3633;
  const Obj S_var_ptrn = 3649;
  const Obj S_var_used = 3665;
  const Obj S_vect_var = 3681;
  const Obj S_atom_type = 3697;
  const Obj S_call_proc = 3713;
  const Obj S_cls_scope = 3729;
  const Obj S_cond_expr = 3745;
  const Obj S_condition = 3761;
  const Obj S_count_var = 3777;
  const Obj S_dupl_tdef = 3793;
  const Obj S_elem_type = 3809;
  const Obj S_empty_map = 3825;
  const Obj S_empty_seq = 3841;
  const Obj S_empty_set = 3857;
  const Obj S_eq_clause = 3873;
  const Obj S_eval_code = 3889;
  const Obj S_fail_stmt = 3905;
  const Obj S_fn_symbol = 3921;
  const Obj S_fndef_err = 3937;
  const Obj S_high_ints = 3953;
  const Obj S_idx_first = 3969;
  const Obj S_in_clause = 3985;
  const Obj S_int_range = 4001;
  const Obj S_is_eq_int = 4017;
  const Obj S_is_ne_map = 4033;
  const Obj S_is_ne_seq = 4049;
  const Obj S_is_ne_set = 4065;
  const Obj S_join_seqs = 4081;
  const Obj S_local_fns = 4097;
  const Obj S_loop_stmt = 4113;
  const Obj S_memb_test = 4129;
  const Obj S_named_par = 4145;
  const Obj S_new_value = 4161;
  const Obj S_op_symbol = 4177;
  const Obj S_or_clause = 4193;
  const Obj S_print_obj = 4209;
  const Obj S_sel_exprs = 4225;
  const Obj S_sequences = 4241;
  const Obj S_start_val = 4257;
  const Obj S_surv_vars = 4273;
  const Obj S_symb_type = 4289;
  const Obj S_terminate = 4305;
  const Obj S_type_ptrn = 4321;
  const Obj S_undef_var = 4337;
  const Obj S_var_redef = 4353;
  const Obj S_var_scope = 4369;
  const Obj S_when_true = 4385;
  const Obj S_and_clause = 4401;
  const Obj S_break_loop = 4417;
  const Obj S_break_stmt = 4433;
  const Obj S_break_vars = 4449;
  const Obj S_exit_block = 4465;
  const Obj S_ext_lookup = 4481;
  const Obj S_greater_eq = 4497;
  const Obj S_is_eq_bool = 4513;
  const Obj S_key_stream = 4529;
  const Obj S_map_it_var = 4545;
  const Obj S_match_expr = 4561;
  const Obj S_membership = 4577;
  const Obj S_merge_maps = 4593;
  const Obj S_print_stmt = 4609;
  const Obj S_range_iter = 4625;
  const Obj S_seq_it_var = 4641;
  const Obj S_seq_to_set = 4657;
  const Obj S_set_it_var = 4673;
  const Obj S_signatures = 4689;
  const Obj S_skip_first = 4705;
  const Obj S_stream_var = 4721;
  const Obj S_syn_fn_def = 4737;
  const Obj S_tagged_obj = 4753;
  const Obj S_tuple_ptrn = 4769;
  const Obj S_tuple_type = 4785;
  const Obj S_ublock_err = 4801;
  const Obj S_union_type = 4817;
  const Obj S_unique_int = 4833;
  const Obj S_unique_var = 4849;
  const Obj S_value_expr = 4865;
  const Obj S_value_ptrn = 4881;
  const Obj S_value_type = 4897;
  const Obj S_when_false = 4913;
  const Obj S_where_expr = 4929;
  const Obj S_assert_stmt = 4945;
  const Obj S_cls_ext_par = 4961;
  const Obj S_get_int_val = 4977;
  const Obj S_get_seq_len = 4993;
  const Obj S_init_stream = 5009;
  const Obj S_lexer_error = 5025;
  const Obj S_list_to_seq = 5041;
  const Obj S_next_var_id = 5057;
  const Obj S_no_ret_stmt = 5073;
  const Obj S_par_typedef = 5089;
  const Obj S_parenthesis = 5105;
  const Obj S_return_stmt = 5121;
  const Obj S_right_arrow = 5137;
  const Obj S_select_expr = 5153;
  const Obj S_seq_to_mset = 5169;
  const Obj S_success_var = 5185;
  const Obj S_tagged_objs = 5201;
  const Obj S_type_symbol = 5217;
  const Obj S_untyped_sgn = 5233;
  const Obj S_using_block = 5249;
  const Obj S_all_rel_vars = 5265;
  const Obj S_builtin_call = 5281;
  const Obj S_cleanup_code = 5297;
  const Obj S_const_or_var = 5313;
  const Obj S_dup_par_tdef = 5329;
  const Obj S_eval_bool_fn = 5345;
  const Obj S_ext_var_ptrn = 5361;
  const Obj S_foreach_stmt = 5377;
  const Obj S_get_curr_key = 5393;
  const Obj S_get_curr_obj = 5409;
  const Obj S_get_map_iter = 5425;
  const Obj S_get_map_size = 5441;
  const Obj S_get_seq_iter = 5457;
  const Obj S_get_set_iter = 5473;
  const Obj S_get_set_size = 5489;
  const Obj S_match_action = 5505;
  const Obj S_move_forward = 5521;
  const Obj S_named_params = 5537;
  const Obj S_obj_proc_def = 5553;
  const Obj S_parser_error = 5569;
  const Obj S_replace_expr = 5585;
  const Obj S_tag_obj_expr = 5601;
  const Obj S_value_stream = 5617;
  const Obj S_accessor_test = 5633;
  const Obj S_almost_def_fn = 5649;
  const Obj S_bool_proc_def = 5665;
  const Obj S_dupl_par_tdef = 5681;
  const Obj S_execute_block = 5697;
  const Obj S_get_inner_obj = 5713;
  const Obj S_get_seq_slice = 5729;
  const Obj S_incomp_fndefs = 5745;
  const Obj S_inf_loop_stmt = 5761;
  const Obj S_internal_sort = 5777;
  const Obj S_is_tagged_obj = 5793;
  const Obj S_map_in_clause = 5809;
  const Obj S_mk_tagged_obj = 5825;
  const Obj S_not_in_clause = 5841;
  const Obj S_retrieve_expr = 5857;
  const Obj S_symbol_switch = 5873;
  const Obj S_dupl_ptrn_vars = 5889;
  const Obj S_dupl_type_pars = 5905;
  const Obj S_empty_map_type = 5921;
  const Obj S_empty_seq_type = 5937;
  const Obj S_empty_set_type = 5953;
  const Obj S_fixed_seq_type = 5969;
  const Obj S_get_curr_value = 5985;
  const Obj S_key_stream_var = 6001;
  const Obj S_select_expr_fn = 6017;
  const Obj S_undef_type_var = 6033;
  const Obj S_assignment_stmt = 6049;
  const Obj S_dup_closure_def = 6065;
  const Obj S_is_out_of_range = 6081;
  const Obj S_nested_local_fn = 6097;
  const Obj S_no_way_out_loop = 6113;
  const Obj S_par_type_symbol = 6129;
  const Obj S_replace_expr_fn = 6145;
  const Obj S_undef_type_name = 6161;
  const Obj S_almost_def_const = 6177;
  const Obj S_dupl_ptrn_labels = 6193;
  const Obj S_nested_fn_symbol = 6209;
  const Obj S_unreachable_code = 6225;
  const Obj S_value_stream_var = 6241;
  const Obj S_add_ref_eval_code = 6257;
  const Obj S_cond_match_action = 6273;
  const Obj S_map_not_in_clause = 6289;
  const Obj S_rep_labels_in_map = 6305;
  const Obj S_asgnm_readonly_var = 6321;
  const Obj S_break_outside_loop = 6337;
  const Obj S_mk_seq_from_stream = 6353;
  const Obj S_mk_set_from_stream = 6369;
  const Obj S_undef_var_or_const = 6385;
  const Obj S_mk_map_from_streams = 6401;
  const Obj S_undef_par_type_name = 6417;
  const Obj S_wrong_num_of_params = 6433;
  const Obj S_already_def_ptrn_var = 6449;
  const Obj S_free_var_in_try_expr = 6465;
  const Obj S_invalid_type_for_tag = 6481;
  const Obj S_undef_bound_ptrn_var = 6497;
  const Obj S_diff_vars_in_or_clause = 6513;
  const Obj S_loc_bound_var_with_ptrn = 6529;
  const Obj S_nested_mult_ptrn_branch = 6545;
  const Obj S_set_found_var_and_leave = 6561;
  const Obj S_eval_expr_and_add_to_set = 6577;
  const Obj S_eval_exprs_and_add_to_map = 6593;
  const Obj S_unbound_vars_in_excl_clause = 6609;
  const Obj S_mult_vars_in_mult_ptrn_branch = 6625;
  const Obj S_vars_repeated_in_diff_branches = 6641;
  const Obj S_incompatible_types_in_union_type = 6657;
  
  
  
  
  const int EMB_SYMB_COUNT = 416;
  
  
  
  
  extern const char *map_symb_to_str[EMB_SYMB_COUNT];
  
  
  
  
  struct Env {
    Obj n_named_params;
  
    Obj n_local_fns;
  
    Obj (*n1_condition)(Obj p0, const Obj *C, Env &env);
    const Obj *C1_condition;
  
    Obj (*n1_eval)(Obj p0, const Obj *C, Env &env);
    const Obj *C1_eval;
  
    Obj (*n2_is_strictly_ordered)(Obj p0, Obj p1, const Obj *C, Env &env);
    const Obj *C2_is_strictly_ordered;
  
    Obj (*n1_f)(Obj p0, const Obj *C, Env &env);
    const Obj *C1_f;
  
    Obj n_typedefs;
  
    Obj n_cls_vars;
  
    Obj n_fns_in_scope;
  
    Obj n_all_par_type_symbols;
  
    Obj n_type_vars_in_scope;
  
    Obj n_type_vars;
  
    Obj n_impl_params;
  
    Obj n_curr_outer_fn;
  
    Obj n_type_map;
  
    Obj n_next_set_it_var_id;
  
    Obj n_next_seq_it_var_id;
  
    Obj n_next_map_it_var_id;
  
    Obj n_next_obj_var_id;
  
    Obj n_next_int_var_id;
  
    Obj n_next_bool_var_id;
  
    Obj n_next_vector_var_id;
  
    Obj n_next_stream_var_id;
  
    Obj (*n1_typesymb2name)(Obj p0, const Obj *C, Env &env);
    const Obj *C1_typesymb2name;
  
    Obj (*n1_cls2id)(Obj p0, const Obj *C, Env &env);
    const Obj *C1_cls2id;
  };
  
  
  
  
  Obj Empty_Set(Env &);
  Obj Empty_Seq(Env &);
  Obj Empty_Map(Env &);
  Obj Unique_Int(Env &);
  Obj Ascii_Minus(Env &);
  Obj Ascii_Space(Env &);
  Obj Ascii_Newline(Env &);
  Obj Ascii_Comma(Env &);
  Obj Ascii_Left_Parenthesis(Env &);
  Obj Ascii_Right_Parenthesis(Env &);
  Obj Terminate(Env &);
  Obj Ascii_Double_Quotes(Env &);
  Obj No_Op(Env &);
  Obj Break_Loop(Env &);
  Obj Ascii_Column(Env &);
  Obj Exit_Block(Env &);
  Obj Ascii_Left_Bracket(Env &);
  Obj Ascii_Right_Bracket(Env &);
  Obj Ascii_Underscore(Env &);
  Obj Ascii_Backslash(Env &);
  Obj Ascii_Left_Brace(Env &);
  Obj Left_Parenthesis(Env &);
  Obj Right_Parenthesis(Env &);
  Obj Left_Bracket(Env &);
  Obj Right_Bracket(Env &);
  Obj Ascii_Right_Brace(Env &);
  Obj Left_Brace(Env &);
  Obj Right_Brace(Env &);
  Obj Obj_True(Env &);
  Obj Obj_False(Env &);
  Obj Obj_Nil(Env &);
  Obj Ret_True(Env &);
  Obj Ret_False(Env &);
  Obj Rand_Sort(Obj, Env &);
  Obj Set(Obj, Env &);
  Obj Left(Obj, Env &);
  Obj Right(Obj, Env &);
  Obj Head(Obj, Env &);
  Obj minus(Obj, Env &);
  Obj Symbol(Obj, Env &);
  Obj Label(Obj, Env &);
  Obj At_Least_One(Obj, Env &);
  Obj Not_All(Obj, Env &);
  Obj Minus(Obj, Env &);
  Obj Neg(Obj, Env &);
  Obj Fn_Par(Obj, Env &);
  Obj And(Obj, Env &);
  Obj Or(Obj, Env &);
  Obj String(Obj, Env &);
  Obj Cls_Ext_Par(Obj, Env &);
  Obj Lvar(Obj, Env &);
  Obj Bvar(Obj, Env &);
  Obj Ivar(Obj, Env &);
  Obj Svar(Obj, Env &);
  Obj Set_It_Var(Obj, Env &);
  Obj Seq_It_Var(Obj, Env &);
  Obj Map_It_Var(Obj, Env &);
  Obj Is_Symb(Obj, Env &);
  Obj Is_Int(Obj, Env &);
  Obj Is_Ne_Set(Obj, Env &);
  Obj Is_Ne_Seq(Obj, Env &);
  Obj Is_Ne_Map(Obj, Env &);
  Obj Is_Tagged_Obj(Obj, Env &);
  Obj Get_Int_Val(Obj, Env &);
  Obj Get_Set_Size(Obj, Env &);
  Obj Get_Seq_Len(Obj, Env &);
  Obj Get_Map_Size(Obj, Env &);
  Obj Get_Tag(Obj, Env &);
  Obj Get_Inner_Obj(Obj, Env &);
  Obj To_Obj(Obj, Env &);
  Obj To_Symb(Obj, Env &);
  Obj Flow_Control_Can_Jump_Out(Obj, Env &);
  Obj Repeat(Obj, Env &);
  Obj Execute_Block(Obj, Env &);
  Obj Ret_Val(Obj, Env &);
  Obj Is_Out_Of_Range(Obj, Env &);
  Obj Init_Stream(Obj, Env &);
  Obj Move_Forward(Obj, Env &);
  Obj Add_Ref(Obj, Env &);
  Obj Release(Obj, Env &);
  Obj And_Then(Obj, Env &);
  Obj Or_Else(Obj, Env &);
  Obj Sort(Obj, Env &);
  Obj Memb_Test(Obj, Env &);
  Obj greater(Obj, Obj, Env &);
  Obj Get_Curr_Obj(Obj, Env &);
  Obj Get_Curr_Key(Obj, Env &);
  Obj Get_Curr_Value(Obj, Env &);
  Obj To_Text(Obj, Env &);
  Obj Seq_Union(Obj, Env &);
  Obj Break_If_Not(Obj, Env &);
  Obj Break_If(Obj, Env &);
  Obj Exit_Block_If_Not(Obj, Env &);
  Obj Exit_Block_If(Obj, Env &);
  Obj Size(Obj, Env &);
  Obj Is_Empty_Set(Obj, Env &);
  Obj Is_Empty_Seq(Obj, Env &);
  Obj Is_Empty_Map(Obj, Env &);
  Obj plus(Obj, Obj, Env &);
  Obj Is_Singleton(Obj, Env &);
  Obj Indexes(Obj, Env &);
  Obj Dec_Seq(Obj, Env &);
  Obj Ret_True_If(Obj, Env &);
  Obj Ret_True_If_Not(Obj, Env &);
  Obj Ret_False_If(Obj, Env &);
  Obj Ret_False_If_Not(Obj, Env &);
  Obj At(Obj, Obj, Env &);
  Obj Is_True(Obj, Env &);
  Obj Is_False(Obj, Env &);
  Obj Check(Obj, Env &);
  Obj Increment(Obj, Env &);
  Obj Sort_Set(Obj, Env &);
  Obj Simplify(Obj, Env &);
  Obj Check_Is_Bool(Obj, Env &);
  Obj Rep_Str(Obj, Obj, Env &);
  Obj Subseq(Obj, Obj, Obj, Env &);
  Obj Rand_Elem(Obj, Env &);
  Obj Get_Curr_Obj(Obj, Obj, Env &);
  Obj Get_Curr_Key(Obj, Obj, Env &);
  Obj Get_Curr_Value(Obj, Obj, Env &);
  Obj Last(Obj, Env &);
  Obj Tail(Obj, Env &);
  Obj Block_Failure_If_Not(Obj, Obj, Env &);
  Obj Is_Bool(Obj, Env &);
  Obj To_Text(Obj, Obj, Env &);
  Obj Subset(Obj, Obj, Env &);
  Obj Disjoint(Obj, Obj, Env &);
  Obj Stmts_Are_Wf(Obj, Obj, Env &);
  Obj Rev_At(Obj, Obj, Env &);
  Obj None(Obj, Env &);
  Obj Substr(Obj, Obj, Obj, Env &);
  Obj Print_Obj(Obj, Env &);
  Obj Is_Between(Obj, Obj, Obj, Env &);
  Obj Maybe_Op(Obj, Obj, Env &);
  Obj Are_Compatible(Obj, Obj, Env &);
  Obj Some(Obj, Env &);
  Obj Ret_False_If_Not_In(Obj, Obj, Env &);
  Obj Set_Found_Var_And_Leave(Obj, Env &);
  Obj Fndef_Wf_Errors(Obj, Obj, Obj, Env &);
  Obj Parse_Obj__Error(Obj, Env &);
  Obj Parse_Prg_Decl(Obj, Env &);
  Obj Syn_Fns_Are_Compatible__Are_Part_Compatible(Obj, Obj, Env &);
  Obj Indent_Line(Obj, Env &);
  Obj Max(Obj, Obj, Env &);
  Obj Min(Obj, Obj, Env &);
  Obj Clause_Wf_Errors(Obj, Obj, Env &);
  Obj Untag(Obj, Env &);
  Obj Has_Duplicates(Obj, Env &);
  Obj Is_Digit(Obj, Env &);
  Obj Is_Lower(Obj, Env &);
  Obj Repeat_While(Obj, Obj, Env &);
  Obj Has_Key(Obj, Obj, Env &);
  Obj Set_To_Mset(Obj, Env &);
  Obj And(Obj, Obj, Env &);
  Obj Or(Obj, Obj, Env &);
  Obj Mk_Call(Obj, Obj, Env &);
  Obj Clauses_Wf_Errors(Obj, Obj, Env &);
  Obj Values(Obj, Env &);
  Obj Only_Element(Obj, Env &);
  Obj Join(Obj, Env &);
  Obj At(Obj, Obj, Obj, Env &);
  Obj Keys(Obj, Env &);
  Obj And_Then(Obj, Obj, Env &);
  Obj Or_Else(Obj, Obj, Env &);
  Obj Indent(Obj, Env &);
  Obj Block_Success_If(Obj, Obj, Env &);
  Obj Block_Failure_If(Obj, Obj, Env &);
  Obj lower_eq(Obj, Obj, Env &);
  Obj greater_eq(Obj, Obj, Env &);
  Obj Multiset_Union(Obj, Env &);
  Obj Can_Fall_Through(Obj, Env &);
  Obj Mk_Call(Obj, Obj, Obj, Env &);
  Obj Normalize_Unions(Obj, Env &);
  Obj Length(Obj, Env &);
  Obj Apply(Obj, Env &);
  Obj Append(Obj, Env &);
  Obj Only_Element(Obj, Obj, Env &);
  Obj Tokenize__Error(Obj, Obj, Env &);
  Obj Fast_Tokenize__Error(Obj, Obj, Env &);
  Obj Vvar(Obj, Obj, Env &);
  Obj Set_Var(Obj, Obj, Env &);
  Obj Set_Bvar(Obj, Obj, Env &);
  Obj Set_Ivar(Obj, Obj, Env &);
  Obj Evar(Obj, Obj, Env &);
  Obj List_To_Seq(Obj, Obj, Env &);
  Obj Internal_Sort(Obj, Obj, Env &);
  Obj Reverse(Obj, Env &);
  Obj Append(Obj, Obj, Env &);
  Obj Mk_Set_From_Stream(Obj, Obj, Env &);
  Obj Mk_Seq_From_Stream(Obj, Obj, Env &);
  Obj Add(Obj, Obj, Env &);
  Obj Rev_Seq(Obj, Obj, Env &);
  Obj Seq_To_Set(Obj, Obj, Env &);
  Obj Seq_To_Mset(Obj, Obj, Env &);
  Obj Eval_Bool_Fn(Obj, Obj, Env &);
  Obj Is_Gt(Obj, Obj, Env &);
  Obj Is_Ge(Obj, Obj, Env &);
  Obj Is_Lt(Obj, Obj, Env &);
  Obj Is_Le(Obj, Obj, Env &);
  Obj Mult(Obj, Obj, Env &);
  Obj Idiv(Obj, Obj, Env &);
  Obj Is_Space(Obj, Env &);
  Obj Union(Obj, Env &);
  Obj Eval_Expr_And_Add_To_Set(Obj, Obj, Env &);
  Obj Gen_Code(Obj, Obj, Env &);
  Obj Untyped_Sgns(Obj, Env &);
  Obj Transitive_Closure__Next_Step(Obj, Obj, Env &);
  Obj To_Text__Is_Left_Par(Obj, Env &);
  Obj To_Text__Is_Right_Par(Obj, Env &);
  Obj Compile_To_C__Arity(Obj, Env &);
  Obj Gen_C_Decl__Arity(Obj, Env &);
  Obj Index_First(Obj, Obj, Env &);
  Obj And(Obj, Obj, Obj, Env &);
  Obj Or(Obj, Obj, Obj, Env &);
  Obj Ublock_Errors(Obj, Obj, Env &);
  Obj And_Then(Obj, Obj, Obj, Env &);
  Obj Or_Else(Obj, Obj, Obj, Env &);
  Obj All_Objects(Env &);
  Obj Intersection(Obj, Obj, Env &);
  Obj Gen_Eval_Code(Obj, Obj, Obj, Env &);
  Obj Difference(Obj, Obj, Env &);
  Obj Exprs_Wf_Errors(Obj, Obj, Env &);
  Obj Var_Scope(Obj, Obj, Obj, Env &);
  Obj Prg_Is_Wf(Obj, Env &);
  Obj Bool_Proc_Def(Obj, Obj, Obj, Env &);
  Obj Union(Obj, Obj, Env &);
  Obj To_C_Fn_Name(Obj, Obj, Env &);
  Obj Set_At(Obj, Obj, Obj, Env &);
  Obj Normalize_Union(Obj, Env &);
  Obj Join_Seqs(Obj, Obj, Obj, Env &);
  Obj Cls_Scope(Obj, Obj, Obj, Obj, Obj, Env &);
  Obj To_C_Fn_Name(Obj, Obj, Obj, Env &);
  Obj Mk_Array(Obj, Obj, Obj, Env &);
  Obj Cases_Wf_Errors(Obj, Obj, Env &);
  Obj Lookup(Obj, Obj, Obj, Env &);
  Obj Ext_Lookup(Obj, Obj, Obj, Env &);
  Obj Get_At(Obj, Obj, Obj, Env &);
  Obj Mk_Set(Obj, Obj, Obj, Env &);
  Obj Mk_Seq(Obj, Obj, Obj, Env &);
  Obj Mk_Tagged_Obj(Obj, Obj, Obj, Env &);
  Obj Call_Proc(Obj, Obj, Obj, Env &);
  Obj Is_Def(Obj, Obj, Obj, Obj, Env &);
  Obj Subexprs(Obj, Env &);
  Obj Call_Cls(Obj, Obj, Obj, Env &);
  Obj Mk_Map_From_Streams(Obj, Obj, Obj, Env &);
  Obj Is_Symbol(Obj, Env &);
  Obj Merge_Maps(Obj, Obj, Obj, Env &);
  Obj Only_Element_Or_Def_If_Empty(Obj, Obj, Env &);
  Obj First_Unused_Int_Var(Obj, Env &);
  Obj star(Obj, Obj, Env &);
  Obj Fn_Call_Is_Wf(Obj, Obj, Obj, Env &);
  Obj Rand_Sort_Pairs(Obj, Env &);
  Obj Syn_Fn_Defs_To_Named_Params(Obj, Obj, Env &);
  Obj Norm_Type(Obj, Env &);
  Obj Par_Parts(Obj, Env &);
  Obj Obj_Proc_Def(Obj, Obj, Obj, Obj, Env &);
  Obj Mk_Fn_Call(Obj, Obj, Obj, Env &);
  Obj Mk_Gen_Call(Obj, Obj, Obj, Obj, Env &);
  Obj Cart_Prod(Obj, Obj, Env &);
  Obj Get_Seq_Slice(Obj, Obj, Obj, Obj, Env &);
  Obj Lookup(Obj, Obj, Obj, Obj, Env &);
  Obj Ext_Lookup(Obj, Obj, Obj, Obj, Env &);
  Obj Cls_Scope(Obj, Obj, Obj, Obj, Env &);
  Obj Mk_Map(Obj, Obj, Obj, Obj, Env &);
  Obj Symbol_To_Token(Obj, Env &);
  Obj Create_Type_Map(Obj, Env &);
  Obj Undef_Type_Symbol_Errs__Make_Err_Obj(Obj, Env &);
  Obj Gen_Fn_Body(Obj, Env &);
  Obj Do_If_In(Obj, Obj, Obj, Env &);
  Obj Is_Almost_Def(Obj, Obj, Obj, Env &);
  Obj Gen_C_Decl__Extra_Params(Obj, Env &);
  Obj Rep_Seq(Obj, Obj, Env &);
  Obj Inc_Seq(Obj, Env &);
  Obj Norm_Type__Norm_Union_Type(Obj, Env &);
  Obj Intersection(Obj, Env &);
  Obj Desugar_Stmts(Obj, Obj, Env &);
  Obj Eval_Exprs_And_Add_To_Map(Obj, Obj, Obj, Obj, Env &);
  Obj Stmts_Wf_Errors(Obj, Obj, Env &);
  Obj Incompatibilities__Are_Syn_Compatible(Obj, Obj, Env &);
  Obj Mk_Assignment(Obj, Obj, Env &);
  Obj Sort_Exprs_First(Obj, Env &);
  Obj Mk_And_Expr(Obj, Env &);
  Obj Do_If_Not_In(Obj, Obj, Obj, Env &);
  Obj Mk_Named_Type_Memb_Test_Fn(Obj, Obj, Env &);
  Obj Norm_Type__Rem_Nesting(Obj, Env &);
  Obj Compile_To_C__Extra_Params(Obj, Env &);
  Obj Compile_To_C__Ret_Type_Str(Obj, Env &);
  Obj Gen_C_Decl__Ret_Type_Str(Obj, Env &);
  Obj Merge_Fns__Mk_Ptrn(Obj, Env &);
  Obj In(Obj, Obj, Env &);
  Obj Do_If_Not(Obj, Obj, Env &);
  Obj Do_If(Obj, Obj, Env &);
  Obj Intermix(Obj, Obj, Env &);
  Obj Merge_Values(Obj, Env &);
  Obj minus(Obj, Obj, Env &);
  Obj Syn_Fndef_To_Fndefs__Syn_Sgns_To_Named_Params(Obj, Env &);
  Obj Has_Return(Obj, Env &);
  Obj Types_Are_Wf__Top_Level_Refs(Obj, Env &);
  Obj Gen_Prg_Code(Obj, Env &);
  Obj Parse_Obj__Parse_Seq(Obj, Obj, Env &);
  Obj Includes(Obj, Obj, Env &);
  Obj Compile_To_C__Typesymb2str(Obj, Obj, Env &);
  Obj Action(Obj, Obj, Env &);
  Obj Arity(Obj, Env &);
  Obj Parse_Obj(Obj, Env &);
  Obj All(Obj, Env &);
  Obj Mk_Gen_Call(Obj, Obj, Obj, Env &);
  Obj Gen_Vector_Eval_Info(Obj, Env &);
  Obj Replace_Bound_Vars(Obj, Obj, Env &);
  Obj Simplify__Make(Obj, Env &);
  Obj Parse_Obj__Parse_Set(Obj, Obj, Env &);
  Obj Are_Compatible(Obj, Env &);
  Obj Is_Def__Could_Match(Obj, Obj, Obj, Obj, Env &);
  Obj To_Nary_Op(Obj, Obj, Obj, Env &);
  Obj Dupl_Elems(Obj, Env &);
  Obj Has_Top_Level_Break(Obj, Env &);
  Obj Sgn_Wf_Errors(Obj, Env &);
  Obj Get_Type_Symbols_To_Instantiate(Obj, Env &);
  Obj Tdef_Errs(Obj, Env &);
  Obj Undef_Type_Symbol_Errs(Obj, Obj, Env &);
  Obj brackets(Obj, Obj, Env &);
  Obj Syn_Fn_Def_To_Expr(Obj, Obj, Env &);
  Obj Transitive_Closure(Obj, Env &);
  Obj Incompatibilities(Obj, Env &);
  Obj Merge_And_Override(Obj, Obj, Env &);
  Obj Par_Tdef_Errs(Obj, Env &);
  Obj Capitalize(Obj, Env &);
  Obj Arity_Is_Correct(Obj, Obj, Env &);
  Obj Branch(Obj, Obj, Obj, Env &);
  Obj Untyped_Sgn(Obj, Env &);
  Obj Syn_Can_Break_Loop(Obj, Env &);
  Obj Undef_Type_Symbol_Errs__All_Type_Symbols(Obj, Env &);
  Obj Lower_Than(Obj, Obj, Env &);
  Obj Mk_And_Clause(Obj, Obj, Env &);
  Obj Partition(Obj, Env &);
  Obj To_Int(Obj, Env &);
  Obj Fndefs_Wf_Errors(Obj, Obj, Env &);
  Obj Are_Compatible__Are_Comp(Obj, Obj, Env &);
  Obj Get_Iter(Obj, Obj, Env &);
  Obj Is_Eq(Obj, Obj, Env &);
  Obj Gen_Eval_Code__Gen_Eval_Expr(Obj, Obj, Env &);
  Obj To_Text__Match_Idxs(Obj, Env &);
  Obj Gen_C_Decl(Obj, Env &);
  Obj Syn_Fns_Are_Compatible(Obj, Obj, Env &);
  Obj Replace_Expr_Fn(Obj, Env &);
  Obj Expr_Is_Wf(Obj, Obj, Env &);
  Obj To_Text__Quote(Obj, Env &);
  Obj Syn_Fndef_To_Fndefs(Obj, Obj, Env &);
  Obj Stmts_Wf_Errors(Obj, Obj, Obj, Obj, Env &);
  Obj Fndef_Wf_Errors(Obj, Obj, Env &);
  Obj Max(Obj, Env &);
  Obj Mk_Cls_Call(Obj, Obj, Obj, Env &);
  Obj Can_Break_Loop(Obj, Env &);
  Obj Cls_Vars(Obj, Env &);
  Obj Inst_Par_Type(Obj, Obj, Env &);
  Obj Inst_Tdef_Errs(Obj, Env &);
  Obj Fn_Def_Errs(Obj, Obj, Obj, Env &);
  Obj To_Text__To_Txt(Obj, Obj, Env &);
  Obj Select_Expr_Fn(Obj, Env &);
  Obj Gen_Code(Obj, Obj, Obj, Obj, Obj, Env &);
  Obj Gen_Eval_Code__Gen_Eval_Instr(Obj, Obj, Obj, Env &);
  Obj Is_Last_For_Sure(Obj, Env &);
  Obj Merge_Partitions(Obj, Env &);
  Obj Block_Wf_Errors(Obj, Obj, Env &);
  Obj Syn_Fndef_To_Fndefs__Mk_Fndef(Obj, Obj, Obj, Obj, Obj, Env &);
  Obj Parse_Obj__Parse_Objs(Obj, Obj, Obj, Env &);
  Obj Gen_Vars(Obj, Env &);
  Obj Parse_Obj__Parse_Obj(Obj, Obj, Env &);
  Obj To_C_Fn_Name(Obj, Env &);
  Obj Gen_Fn_Code(Obj, Env &);
  Obj Subseq(Obj, Obj, Obj, Obj, Env &);
  Obj Syn_Is_Last_For_Sure(Obj, Env &);
  Obj Gen_Eval_Info(Obj, Obj, Env &);
  Obj Stmts_Are_Wf(Obj, Obj, Obj, Obj, Env &);
  Obj Case_Wf_Errors(Obj, Obj, Env &);
  Obj Iter_Wf_Errors(Obj, Obj, Env &);
  Obj Never_Falls_Through(Obj, Env &);
  Obj Mergesort__Merge(Obj, Obj, Env &);
  Obj Types_Are_Wf(Obj, Env &);
  Obj Merge_Fns_Same_Name_And_Arity(Obj, Env &);
  Obj Mergesort(Obj, Env &);
  Obj Scalar_Vars(Obj, Env &);
  Obj To_Str(Obj, Env &);
  Obj Merge_Fns(Obj, Env &);
  Obj lower(Obj, Obj, Env &);
  Obj Gen_Vector_Eval_Info__Gen_Vector_Eval_Code(Obj, Obj, Obj, Env &);
  Obj Case_Is_Wf(Obj, Obj, Obj, Env &);
  Obj Gen_Type_Checking_Expr(Obj, Obj, Env &);
  Obj Fndefs_Are_Wf(Obj, Env &);
  Obj Vars_To_Declare(Obj, Env &);
  Obj Gen_C_Decl(Obj, Obj, Env &);
  Obj Are_Disjoint(Obj, Obj, Env &);
  Obj Inst_Req_Par_Types(Obj, Env &);
  Obj Gen_Eval_Info(Obj, Env &);
  Obj Special_Subexprs(Obj, Env &);
  Obj Parse_Obj__Parse_Tagged_Obj_Or_Symbol(Obj, Obj, Env &);
  Obj amp(Obj, Obj, Env &);
  Obj Rem_Syntax(Obj, Env &);
  Obj Extern_Vars__Special_Cases(Obj, Env &);
  Obj Simplify__Make(Obj, Obj, Obj, Obj, Obj, Env &);
  Obj Flow_Control_Can_Jump_Out(Obj, Obj, Env &);
  Obj Untyped_Sgn(Obj, Obj, Env &);
  Obj Fndef_Is_Wf(Obj, Obj, Env &);
  Obj To_Text__To_Txt(Obj, Env &);
  Obj Clause_Is_Wf(Obj, Obj, Env &);
  Obj Fndef_Wf_Errors(Obj, Obj, Obj, Obj, Env &);
  Obj To_Text__Wrap(Obj, Obj, Env &);
  Obj Fn_Call_Is_Wf__Could_Match(Obj, Obj, Obj, Env &);
  Obj Gen_Code(Obj, Env &);
  Obj Desugar_Clause(Obj, Obj, Env &);
  Obj Expr_Is_Wf__Rest_Is_Wf(Obj, Obj, Env &);
  Obj Compile(Obj, Env &);
  Obj Make_Scopes(Obj, Obj, Env &);
  Obj Parse_Obj__Parse_Map_Or_Tuple(Obj, Obj, Env &);
  Obj Syn_New_Vars(Obj, Env &);
  Obj Var_Decl(Obj, Env &);
  Obj Clause_Wf_Errors(Obj, Obj, Obj, Env &);
  Obj New_Vars(Obj, Env &);
  Obj Ptrn_Is_Wf(Obj, Obj, Env &);
  Obj Partitions(Obj, Env &);
  Obj To_C_Var_Name(Obj, Env &);
  Obj Stmt_Wf_Errors(Obj, Obj, Obj, Obj, Env &);
  Obj Ptrn_Wf_Errors(Obj, Obj, Env &);
  Obj Stmt_Is_Wf(Obj, Obj, Obj, Env &);
  Obj Gen_Ptrn_Matching_Code(Obj, Obj, Obj, Env &);
  Obj Type_Wf_Errors(Obj, Env &);
  Obj Type_Is_Wf(Obj, Obj, Env &);
  Obj Ordinary_Subexprs(Obj, Env &);
  Obj Extern_Vars(Obj, Env &);
  Obj Tokenize(Obj, Env &);
  Obj Fast_Tokenize(Obj, Env &);
  Obj Wf_Errors(Obj, Env &);
  Obj Desugar_Stmt(Obj, Obj, Env &);
  Obj Gen_Iter_Code(Obj, Obj, Env &);
  Obj To_C_Expr(Obj, Env &);
  Obj Compile_To_C(Obj, Obj, Obj, Env &);
  Obj Gen_Code(Obj, Obj, Obj, Obj, Env &);
  Obj Gen_Type_Checking_Code(Obj, Obj, Obj, Env &);
  Obj Expr_Wf_Errors(Obj, Obj, Env &);
  Obj To_C_Expr(Obj, Obj, Env &);
  Obj Desugar_Expr(Obj, Obj, Env &);
  Obj Gen_Eval_Code(Obj, Obj, Env &);
  Obj Compile_To_C(Obj, Env &);
  Obj Compile_To_C(Obj, Obj, Env &);
  
  
  
  
}
